name: Interiordesign
favicon: null
layout_spectrum: 0.16694
typography_spectrum: 0.49582
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#82afc6'
    - '#3a3c4b'
    - '#f4e8e8'
    - '#035fbc'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
