title: Jamie Keegan - Portfolio
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0.5018797
  lightness: 0.5
  brandColors:
    - '#020204'
    - '#82afc6'
    - '#3a3c4b'
    - '#f4e8e8'
    - '#035fbc'
  rhythmicContrast: 0.1898496
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Interiordesign
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49582
layout_spectrum: 0.5576441
