name: Interiordesign
favicon: null
layout_spectrum: 0.33889
typography_spectrum: 0.49582
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0085e0'
    - '#c9cbc8'
    - '#000002'
    - '#71746d'
    - '#46bcfa'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
