name: Interiordesign
favicon: null
layout_spectrum: 0.29215
typography_spectrum: 0.66611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#252525'
    - '#9e9e9e'
    - '#676767'
    - '#c2c2c2'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
