name: Interiordesign
favicon: null
layout_spectrum: 0.33889
typography_spectrum: 0.49582
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d6d6d6'
    - '#bcbcbc'
    - '#a2a2a2'
    - '#7b7b7b'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
