name: Interiordesign
favicon: null
layout_spectrum: 0.74123
typography_spectrum: 0.1636
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#252525'
    - '#9e9e9e'
    - '#676767'
    - '#c2c2c2'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
