name: Interiordesign
favicon: null
layout_spectrum: 0.29215
typography_spectrum: 0.6394
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd8d5'
    - '#5eab99'
    - '#484b49'
    - '#3f6991'
    - '#838381'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
