name: Interiordesign
favicon: null
layout_spectrum: 0.33889
typography_spectrum: 0.49582
title: Jamie Keegan - Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdfb'
    - '#daa5b7'
    - '#d3d6c1'
    - '#55342b'
    - '#a1735c'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
